version: 2

sources:
  - name: live
    database: appropriate_database_name  # Replace with actual database name
    schema: live
    tables:
      - name: FACT_AR_INVOICE_LINEITEM
      - name: FACT_ACCOUNTING_DOCUMENT_HEADER
      - name: FACT_AR_INVOICE_BILLING_ITEMS
      - name: FACT_ACCOUNTING_DOCUMENT_LINE_ITEMS
      - name: dim_customer
      - name: dim_payment_terms

  - name: fdh_slt_raw
    database: appropriate_database_name  # Replace with actual database name
    schema: fdh_slt_raw
    tables:
      - name: dim_xxetn_map_unit_sap_ora
      - name: dim_bu_heirarchy
