With MinDocumentLineNumber AS (
    SELECT FISCAL_YEAR, LEGAL_ENTITY, DOCUMENT_NUMBER, Min(DOCUMENT_LINE_NUMBER) AS min_DOCUMENT_LINE_NUMBER
    FROM FactArInvoiceLineItem
    GROUP BY FISCAL_YEAR, LEGAL_ENTITY, DOCUMENT_NUMBER
)

Select * from MinDocumentLineNumber