Select a.policy_key,
			a.extract_key,
			IFNULL(TRIM(a.agency_system_policy_id), '') AS policy_id,
			a.office_agency_system_key,
			a.client_key,
			a.broker_key,
			a.insurer_market_key,
			a.payee_market_key,
			a.product_line_key,
			a.producer1_employee_key,
			a.producer2_employee_key,
			a.csr1_employee_key,
			a.department_key,
			a.policy_number AS policy_num,
			a.policy_status,
			NULLIF(TO_DATE(a.effective_date), '1900-01-01 00:00:00.000') AS effective_date,
			NULLIF(TO_DATE(a.expiration_date), '1900-01-01 00:00:00.000') AS expiration_date,
			NULLIF(TO_DATE(a.inception_date), '1900-01-01 00:00:00.000') AS inception_date,
			a.estimated_premium AS estimated_premium_amt,
			a.epic_policy_type_key,
			a.annualized_endorsement_premium AS annualized_endorsement_premium_amt,
			a.written_premium AS written_premium_amt,
			a.annualized_premium AS annualized_premium_amt,
			NULLIF(TO_DATE(a.contracted_expiration_date), '1900-01-01 00:00:00.000') AS contracted_expiration_date 
from {{ ref('s_dim_policy_UC5') }} as a