version: 2

sources:
  - name: SAP
    database: colint_dev
    schema: LIVE
    tables:
      - name: FACT_AR_INVOICE_LINEITEM
      - name: FACT_ACCOUNTING_DOCUMENT_HEADER
      - name: FACT_AR_INVOICE_BILLING_ITEMS
      - name: FACT_ACCOUNTING_DOCUMENT_LINE_ITEMS
      - name: dim_customer
      - name: dim_payment_terms

  - name: fdh_sap
    database: colint_dev
    schema: slt_raw
    tables:
      - name: dim_xxetn_map_unit_sap_ora
      - name: dim_bu_heirarchy
      
