-- models/f_policy_EPIC_US.sql

{{ config(materialized='table') }}

WITH source_data AS (
    SELECT * FROM {{ ref('int_policy_EPIC_US_combined') }}
),

final_data AS (
    SELECT
        policy_key,
        client_key,
        carrier_insurer_key,
        carrier_payee_key,
        product_key,
        product_line_key,
        producer_01_key,
        producer_02_key,
        account_manager_key,
        effective_date_key,
        expiration_date_key,
        inception_date_key,
        cancel_date_key,
        reinstated_date_key,
        invoice_date_key,
        contracted_expiration_date_key,
        client_producer_key,
        client_account_manager_key,
        bu_key,
        bu_department_key,
        bu_state_key,
        renewal_policy_key,
        prior_market_key,
        future_market_key,
        renewal_date_key,
        financing_company_key,
        excess_policy_key,
        source_system_key,
        source_system_instance_key,
        bill_type_key,
        active_policy_status_key,
        ajg_new_client_status_key,
        ajg_lost_business_detail_key,
        ajg_lost_client_status_key,
        ajg_new_business_detail_key,
        fee_converted_lost_detail_key,
        fee_converted_new_detail_key,
        fee_split_lost_detail_key,
        fee_split_new_detail_key,
        future_market_type_key,
        market_status_key,
        prior_market_type_key,
        package_converted_lost_detail_key,
        package_converted_new_detail_key,
        policy_occurrence_key,
        'EPIC_US' AS env_source_code, -- Hardcoded, could be made dynamic
        data_source_code,
        annualized_endorsement_premium_amt,
        written_premium_amt,
        annualized_premium_amt,
        estimated_premium_amt,
        agent_commission_amt_lcl,
        agent_commission_amt_usd,
        agent_commission_amt_pegusd,
        agent_commission_amt_trns,
        billed_premium_amt_lcl,
        billed_premium_amt_usd,
        billed_premium_amt_pegusd,
        billed_premium_amt_trns,
        brokerage_expense_amt_lcl,
        brokerage_expense_amt_usd,
        brokerage_expense_amt_pegusd,
        brokerage_expense_amt_trns,
        commission_revenue_amt_lcl,
        commission_revenue_amt_usd,
        commission_revenue_amt_pegusd,
        commission_revenue_amt_trns,
        fee_revenue_amt_lcl,
        fee_revenue_amt_usd,
        fee_revenue_amt_pegusd,
        fee_revenue_amt_trns,
        commission_premium_amt_lcl,
        commission_premium_amt_usd,
        commission_premium_amt_pegusd,
        commission_premium_amt_trns,
        fee_premium_amt_lcl,
        fee_premium_amt_usd,
        fee_premium_amt_pegusd,
        fee_premium_amt_trns
    FROM source_data
)

SELECT * FROM final_data