-- models/intermediate/int_policy_EPIC_US_combined.sql

{{ config(materialized='ephemeral') }}

SELECT
    a.*,
    b.renewal_policy_key,
    c.prior_market_key,
    c.future_market_key,
    c.active_policy_status_key,
    c.ajg_new_client_status_key,
    c.ajg_lost_business_detail_key,
    c.ajg_lost_client_status_key,
    c.ajg_new_business_detail_key,
    c.fee_converted_lost_detail_key,
    c.fee_converted_new_detail_key,
    c.fee_split_lost_detail_key,
    c.fee_split_new_detail_key,
    c.future_market_type_key,
    c.market_status_key,
    c.prior_market_type_key,
    c.package_converted_lost_detail_key,
    c.package_converted_new_detail_key,
    c.policy_occurrence_key,
    c.active_policy_status_code,
    c.ajg_new_client_status_code,
    c.ajg_lost_business_detail_code,
    c.ajg_lost_client_status_code,
    c.ajg_new_business_detail_code,
    c.fee_converted_lost_detail_code,
    c.fee_converted_new_detail_code,
    c.fee_split_lost_detail_code,
    c.fee_split_new_detail_code,
    c.future_market_type_code,
    c.market_status_code,
    c.prior_market_type_code,
    c.package_converted_lost_detail_code,
    c.package_converted_new_detail_code,
    c.policy_occurrence_code,
    -- Include fields from the revenue detail model
    COALESCE(d.bu_key, a.bu_key) AS bu_key,
    COALESCE(d.bu_department_key, a.bu_department_key) AS bu_department_key,
    COALESCE(d.bu_state_key, a.bu_state_key) AS bu_state_key,
    COALESCE(d.client_key, a.client_key) AS client_key,
    COALESCE(d.carrier_insurer_key, a.carrier_insurer_key) AS carrier_insurer_key,
    COALESCE(d.carrier_payee_key, a.carrier_payee_key) AS carrier_payee_key,
    COALESCE(d.product_key, a.product_key) AS product_key,
    COALESCE(d.product_line_key, a.product_line_key) AS product_line_key,
    COALESCE(d.producer_01_key, a.producer_01_key) AS producer_01_key,
    COALESCE(d.client_producer_key, a.client_producer_key) AS client_producer_key,
    COALESCE(d.client_account_manager_key, a.client_account_manager_key) AS client_account_manager_key,
    d.invoice_date_key,
    COALESCE(d.bill_type_key, a.bill_type_key) AS bill_type_key,
    d.agent_commission_amt_lcl,
    d.agent_commission_amt_usd,
    d.agent_commission_amt_pegusd,
    d.agent_commission_amt_trns,
    d.billed_premium_amt_lcl,
    d.billed_premium_amt_usd,
    d.billed_premium_amt_pegusd,
    d.billed_premium_amt_trns,
    d.brokerage_expense_amt_lcl,
    d.brokerage_expense_amt_usd,
    d.brokerage_expense_amt_pegusd,
    d.brokerage_expense_amt_trns,
    d.commission_revenue_amt_lcl,
    d.commission_revenue_amt_usd,
    d.commission_revenue_amt_pegusd,
    d.commission_revenue_amt_trns,
    d.fee_revenue_amt_lcl,
    d.fee_revenue_amt_usd,
    d.fee_revenue_amt_pegusd,
    d.fee_revenue_amt_trns,
    d.commission_premium_amt_lcl,
    d.commission_premium_amt_usd,
    d.commission_premium_amt_pegusd,
    d.commission_premium_amt_trns,
    d.fee_premium_amt_lcl,
    d.fee_premium_amt_usd,
    d.fee_premium_amt_pegusd,
    d.fee_premium_amt_trns
FROM {{ ref('stg_policy_EPIC_US_main') }} a
LEFT JOIN {{ ref('stg_policy_EPIC_US_renewal') }} b ON a.policy_key = b.policy_key
LEFT JOIN {{ ref('stg_policy_EPIC_US_lifecycle_attr') }} c ON a.policy_key = c.policy_key
LEFT JOIN {{ ref('int_policy_EPIC_US_revenue_detail') }} d ON a.policy_key = d.policy_key